@startuml
left to right direction

actor User

rectangle "Todo List" {
  usecase "Create Todo" as UC1
  usecase "Get Todo by ID" as UC2
  usecase "Update Todo" as UC3
  usecase "Delete Todo" as UC4
  usecase "List Todos" as UC5
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5

@enduml

